keywords:
- マクドナルド
- スターバックス
- ドトール
- サイゼリヤ
- 吉野家
- 松屋
- すき家
- ガスト
- ジョナサン
- ケンタッキー
- モスバーガー
- 大戸屋
- 日高屋
- 餃子の王将
- 大阪王将
- タリーズ
- エクセルシオール
- ロッテリア
- てんや
- はなまるうどん
- 丸亀製麺
- 富士そば
- ココイチ
- CoCo壱番屋
- スシロー
- くら寿司
- かっぱ寿司
- 串カツ田中
- 鳥貴族
- ガパオ
- プロント
- ベローチェ
- 居酒屋革命 酔っ手羽 品川港南口店
- 喫茶室ルノアール
- PRONTO
- バーミヤン
nationwide_threshold: 8
